name: Test Sling Action

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  actions-test:
    runs-on: ubuntu-latest
    env:
      TEST_PG_SLING_MASTER: ${{ secrets.TEST_PG_SLING_MASTER }}
      DEMO_POSTGRES: ${{ secrets.DEMO_POSTGRES }}

    steps:
      - uses: actions/checkout@v2
      
      - name: List Connections
        uses: ./
        with:
          command: conns list
        
      - name: Run Replication
        uses: ./
        with:
          command: run -r test_replication.yml
